//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dapesa.Tesoreria.Bancos.Reglas.Proxy {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Definiciones.TipoCifrado", Namespace="http://schemas.datacontract.org/2004/07/Dapesa.Criptografia.Comun")]
    public enum DefinicionesTipoCifrado : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AES = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MD5 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SHA1 = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Definiciones.TipoSentencia", Namespace="http://schemas.datacontract.org/2004/07/Dapesa.AccesoDatos.Comun")]
    public enum DefinicionesTipoSentencia : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Escalar = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoQuery = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Query = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Definiciones.TipoManejadorTransaccion", Namespace="http://schemas.datacontract.org/2004/07/Dapesa.AccesoDatos.Comun")]
    public enum DefinicionesTipoManejadorTransaccion : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContinuarTransaccion = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FinalizarTransaccion = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IniciarTransaccion = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoTransaccion = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Definiciones.TipoResultado", Namespace="http://schemas.datacontract.org/2004/07/Dapesa.AccesoDatos.Comun")]
    public enum DefinicionesTipoResultado : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cadena = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Conjunto = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Decimal = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Entero = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Vacio = -1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxy.IDespachador")]
    public interface IDespachador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDespachador/Validar", ReplyAction="http://tempuri.org/IDespachador/ValidarResponse")]
        bool Validar(Dapesa.Comun.Entidades.Conexion poConexion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDespachador/Despachar", ReplyAction="http://tempuri.org/IDespachador/DespacharResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Dapesa.Comun.Entidades.Conexion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Dapesa.Comun.Entidades.Credenciales))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Dapesa.Criptografia.Reglas.Cifrado))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Dapesa.Tesoreria.Bancos.Reglas.Proxy.DefinicionesTipoCifrado))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Dapesa.Comun.Definiciones.TipoConexion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Dapesa.Comun.Definiciones.TipoCliente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Dapesa.AccesoDatos.Entidades.Sentencia>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Dapesa.AccesoDatos.Entidades.Sentencia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Dapesa.AccesoDatos.Entidades.Parametro>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Dapesa.AccesoDatos.Entidades.Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Data.ParameterDirection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Data.DbType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Data.CommandType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Dapesa.Tesoreria.Bancos.Reglas.Proxy.DefinicionesTipoSentencia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Dapesa.Tesoreria.Bancos.Reglas.Proxy.DefinicionesTipoManejadorTransaccion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Dapesa.Tesoreria.Bancos.Reglas.Proxy.DefinicionesTipoResultado))]
        object Despachar(Dapesa.Comun.Entidades.Conexion poConexion, System.Collections.Generic.List<Dapesa.AccesoDatos.Entidades.Sentencia> poSentencia);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDespachadorChannel : Dapesa.Tesoreria.Bancos.Reglas.Proxy.IDespachador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DespachadorClient : System.ServiceModel.ClientBase<Dapesa.Tesoreria.Bancos.Reglas.Proxy.IDespachador>, Dapesa.Tesoreria.Bancos.Reglas.Proxy.IDespachador {
        
        public DespachadorClient() {
        }
        
        public DespachadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DespachadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DespachadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DespachadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Validar(Dapesa.Comun.Entidades.Conexion poConexion) {
            return base.Channel.Validar(poConexion);
        }
        
        public object Despachar(Dapesa.Comun.Entidades.Conexion poConexion, System.Collections.Generic.List<Dapesa.AccesoDatos.Entidades.Sentencia> poSentencia) {
            return base.Channel.Despachar(poConexion, poSentencia);
        }
    }
}
