//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dapesa.Almacen.Pedidos.IU.Mensajero {
    
    
    public partial class Default {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Dapesa.Almacen.Pedidos.IU.Mensajero.Site Master {
            get {
                return ((Dapesa.Almacen.Pedidos.IU.Mensajero.Site)(base.Master));
            }
        }
    }
}
