//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dapesa.Comun.DirectorioActivo.IU.Directorio {
	
	
	public partial class Default {
		
		/// <summary>
		/// Master property.
		/// </summary>
		/// <remarks>
		/// Auto-generated property.
		/// </remarks>
		public new Dapesa.Comun.DirectorioActivo.IU.Directorio.Site Master {
			get {
				return ((Dapesa.Comun.DirectorioActivo.IU.Directorio.Site)(base.Master));
			}
		}
	}
}
