//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dapesa.Credito.Informes.IU.ClientesPlazoPagoNeto {
    
    
    public partial class Default {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Dapesa.Credito.Informes.IU.ClientesPlazoPagoNeto.Site Master {
            get {
                return ((Dapesa.Credito.Informes.IU.ClientesPlazoPagoNeto.Site)(base.Master));
            }
        }
    }
}
