//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dapesa.Credito.Documentos.Reglas.Proxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cifrado", Namespace="http://schemas.datacontract.org/2004/07/Dapesa.Criptografia.Reglas")]
    [System.SerializableAttribute()]
    public partial class Cifrado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dapesa.Credito.Documentos.Reglas.Proxy.DefinicionesTipoCifrado _oAlgoritmoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] _oLlaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] _oVectorInicializacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dapesa.Credito.Documentos.Reglas.Proxy.DefinicionesTipoCifrado _oAlgoritmo {
            get {
                return this._oAlgoritmoField;
            }
            set {
                if ((this._oAlgoritmoField.Equals(value) != true)) {
                    this._oAlgoritmoField = value;
                    this.RaisePropertyChanged("_oAlgoritmo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] _oLlave {
            get {
                return this._oLlaveField;
            }
            set {
                if ((object.ReferenceEquals(this._oLlaveField, value) != true)) {
                    this._oLlaveField = value;
                    this.RaisePropertyChanged("_oLlave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] _oVectorInicializacion {
            get {
                return this._oVectorInicializacionField;
            }
            set {
                if ((object.ReferenceEquals(this._oVectorInicializacionField, value) != true)) {
                    this._oVectorInicializacionField = value;
                    this.RaisePropertyChanged("_oVectorInicializacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Definiciones.TipoCifrado", Namespace="http://schemas.datacontract.org/2004/07/Dapesa.Criptografia.Comun")]
    public enum DefinicionesTipoCifrado : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AES = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MD5 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SHA1 = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Definiciones.TipoConexion", Namespace="http://schemas.datacontract.org/2004/07/Dapesa.Comun")]
    public enum DefinicionesTipoConexion : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CredencialesExplicitas = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NombreConexion = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoTNSNAMES = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Definiciones.TipoCliente", Namespace="http://schemas.datacontract.org/2004/07/Dapesa.Comun")]
    public enum DefinicionesTipoCliente : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MySql = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Oracle = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SqlServer = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxy.IDespachador")]
    public interface IDespachador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDespachador/Validar", ReplyAction="http://tempuri.org/IDespachador/ValidarResponse")]
        bool Validar(Dapesa.Comun.Entidades.Conexion poConexion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDespachador/Despachar", ReplyAction="http://tempuri.org/IDespachador/DespacharResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Dapesa.Comun.Entidades.Conexion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Dapesa.Comun.Entidades.Credenciales))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Dapesa.Credito.Documentos.Reglas.Proxy.Cifrado))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Dapesa.Credito.Documentos.Reglas.Proxy.DefinicionesTipoCifrado))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Dapesa.Credito.Documentos.Reglas.Proxy.DefinicionesTipoConexion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Dapesa.Credito.Documentos.Reglas.Proxy.DefinicionesTipoCliente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Dapesa.AccesoDatos.Entidades.Sentencia>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Dapesa.AccesoDatos.Entidades.Sentencia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Dapesa.AccesoDatos.Entidades.Parametro>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Dapesa.AccesoDatos.Entidades.Parametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Data.ParameterDirection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Data.DbType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Data.CommandType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Dapesa.AccesoDatos.Comun.Definiciones.TipoSentencia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Dapesa.AccesoDatos.Comun.Definiciones.TipoManejadorTransaccion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Dapesa.AccesoDatos.Comun.Definiciones.TipoResultado))]
        object Despachar(Dapesa.Comun.Entidades.Conexion poConexion, System.Collections.Generic.List<Dapesa.AccesoDatos.Entidades.Sentencia> poSentencia);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDespachadorChannel : Dapesa.Credito.Documentos.Reglas.Proxy.IDespachador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DespachadorClient : System.ServiceModel.ClientBase<Dapesa.Credito.Documentos.Reglas.Proxy.IDespachador>, Dapesa.Credito.Documentos.Reglas.Proxy.IDespachador {
        
        public DespachadorClient() {
        }
        
        public DespachadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DespachadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DespachadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DespachadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Validar(Dapesa.Comun.Entidades.Conexion poConexion) {
            return base.Channel.Validar(poConexion);
        }
        
        public object Despachar(Dapesa.Comun.Entidades.Conexion poConexion, System.Collections.Generic.List<Dapesa.AccesoDatos.Entidades.Sentencia> poSentencia) {
            return base.Channel.Despachar(poConexion, poSentencia);
        }
    }
}
