//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Credito.Clientes.Cartera.UI.AnalisisCliente {
    
    
    public partial class Default {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Credito.Clientes.Cartera.UI.AnalisisCliente.Site Master {
            get {
                return ((Credito.Clientes.Cartera.UI.AnalisisCliente.Site)(base.Master));
            }
        }
    }
}
